### ISSUE TITLE
Footer positioning

### ISSUE THREAD

**Issue by danko-ui** [ITISHub/frontend#1]
Нужно правильно позиционировать footer приложения, чтобы при малом количестве контента на странице он просто "прилипал к дну страницы", но при этом адекватно отображался на экранах, где контент изначально занимает достаточную часть viewport'a: 

**Пример, где footer ведет себя не верно (position: absolute), при достаточном количестве контента** 

![image](https://user-images.githubusercontent.com/44056222/89375371-2fc59c00-d6f6-11ea-8280-6cfbe4685fc2.png)

**Но с position: absolute footer верно отображается на нестандартных экранах, где контента, по сравнению с высотой viewport'a мало** 

![image](https://user-images.githubusercontent.com/44056222/89375556-977be700-d6f6-11ea-9be3-e98ff0d5cf43.png)

**Comment by danko-ui** [comment]
Полезные ссылки: 
* https://vuetifyjs.com/ru/components/footer/ - о компоненте footer'a
* https://vuetifyjs.com/en/components/application/ - об относительном расположении компонентов

**Comment by danko-ui** [comment]
Поясняю один момент, структура страницы наглядно в директории **itis-hub/layouts/default**, сам компонент footer'a в **itis-hub/components/FooterBar.vue**

**Comment by AnteeOne** [comment]
@chackydude , у меня footer вроде отображается верно , даже при обильном количестве контента o_O

**Comment by danko-ui** [comment]
Окей, @AnteeOne, поясню, в master'e не абсолютный footer (его нужно сделать абсолютным, т.е. чтобы "прилипал ко дну" и отображался не перекрывая контент), и отображение нормальное только как раз таки при большом количестве контента, если его недостаточно footer съезжает вверх (для наглядности можешь поиграться с масштабом странички, уменьшить его до 40-50%)

**Comment by chackydude** [comment]
Fixed with using div-wrapper for FooterBar component. (absolute v-footer is absolute only for his parrent).

**Comment by danko-ui** [comment]
Fixed with using div-wrapper for FooterBar component. (absolute v-footer is absolute only for his parrent).
