### ISSUE TITLE
Review Form(email validation &&closing form after sending)

### ISSUE THREAD

**Issue by AnteeOne** [ITISHub/frontend#2]
I think , we need to add email validation in review form to minimize count of casual sending
That you think about it , @chackydude ?
![image](https://user-images.githubusercontent.com/57267956/89805396-42990000-db3e-11ea-9969-e42f250be226.png)

**Comment by danko-ui** [comment]
@AnteeOne , that's a good idea, i will try to do it ^^

**Comment by danko-ui** [comment]
@AnteeOne, you can close this issie after tests

**Comment by AnteeOne** [comment]
i have tested it just , soo , form is working , so we can close this issue :trollface:👍
